### ISSUE TITLE
ffmpeg keyframe seeking issue

### ISSUE THREAD

**Issue by changil** [changil/avspeech-downloader#1]
`ffmpeg` uses keyframe seeking when stream copying. Consequently, when a cut boundary doesn't fall at a keyframe (which happens most of the time) it cuts from the previous keyframe and sets a negative start time to compensate it. So any subsequent tools that take the cut video clips should take the start time into account. Most video players do, but if you programatically process video clips, you should do it yourself and discard first part of both audio and video accordingly. A fix would be to transcode video when cutting, at the cost of extended processing time. I will push a patch soon.

Affected lines of code:

https://github.com/changil/avspeech-downloader/blob/ab3bb4959489e5073ed5d7635c5a1d6777b5d9be/download.sh#L94

https://github.com/changil/avspeech-downloader/blob/ab3bb4959489e5073ed5d7635c5a1d6777b5d9be/download.sh#L107

**Comment by dingzeyuli** [comment]
If the start time becomes negative, how can I detect that in code? Do you have a sample video? Thanks.

**Comment by changil** [comment]
Here's an example. I intend to cut a video clip between 10 and 14 seconds from the beginning.

```bash
$ ffmpeg -y -loglevel error -ss 10 -i "$(youtube-dl -f 22 -g AvWWVOgaMlk)" -t 4 -c:v copy -c:a copy sample.mp4 < /dev/null && ffprobe sample.mp4 2>&1 | grep start
  Duration: 00:00:09.06, start: -5.054150, bitrate: 1669 kb/s
```

But the closest preceding keyframe is about 5.05 seconds earlier at around 10 - 5.05 = 4.95 seconds, and that's where the actual cut took place. The length of the clip was also increased by about 5.05 seconds, resulting in 9.06 seconds instead of 4.

Recent `ffprobe` seems to report 0 when `start_time` is negative. In my machine, `ffmpeg` 2.8 reports a correct `start_time`, but `ffmpeg` 4.1 doesn't. `mplayer` could be used instead then.

```bash
$ mplayer -identify -frames 0 -vc null -vo null -ao null sample.mp4 2>&1 | grep -i start_time
ID_START_TIME=-5.05
```

`ffmpeg` appears to respect `start_time` if you subsequently process cut video clips using it, e.g., split audio from video. I don't know if other tool kits provide a way to get either `start_time` or per-frame timestamps.

**Comment by changil** [comment]
It seems like the only foolproof option would be to transcode the portion of video that's being cut. In this way, frames are re-encoded always and cuts are frame-accurate even if they don't fall at keyframes, but it could take a (much) longer time. Please let me know if anyone's aware of a better solution.
